//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] adb {
            get {
                object obj = ResourceManager.GetObject("adb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap adb1 {
            get {
                object obj = ResourceManager.GetObject("adb1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AdbWinApi {
            get {
                object obj = ResourceManager.GetObject("AdbWinApi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AdbWinUsbApi {
            get {
                object obj = ResourceManager.GetObject("AdbWinUsbApi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apk {
            get {
                object obj = ResourceManager.GetObject("apk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap app_0 {
            get {
                object obj = ResourceManager.GetObject("app_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap automation_0 {
            get {
                object obj = ResourceManager.GetObject("automation_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] avcodec_61 {
            get {
                object obj = ResourceManager.GetObject("avcodec_61", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] avformat_61 {
            get {
                object obj = ResourceManager.GetObject("avformat_61", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] avutil_59 {
            get {
                object obj = ResourceManager.GetObject("avutil_59", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap capture {
            get {
                object obj = ResourceManager.GetObject("capture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chupmanhinh {
            get {
                object obj = ResourceManager.GetObject("chupmanhinh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cuahang_0 {
            get {
                object obj = ResourceManager.GetObject("cuahang_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] curl {
            get {
                object obj = ResourceManager.GetObject("curl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dark_mode {
            get {
                object obj = ResourceManager.GetObject("dark_mode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] data {
            get {
                object obj = ResourceManager.GetObject("data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dieukhien_0 {
            get {
                object obj = ResourceManager.GetObject("dieukhien_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] eng {
            get {
                object obj = ResourceManager.GetObject("eng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileEdit {
            get {
                object obj = ResourceManager.GetObject("fileEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help_0 {
            get {
                object obj = ResourceManager.GetObject("help_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Copyright (C) 2012 The Android Open Source Project
        ///#
        ///# IMPORTANT: Do not create world writable files or directories.
        ///# This is a common source of Android security bugs.
        ///#
        ///
        ///import /init.environ.rc
        ///import /init.usb.rc
        ///import /init.${ro.hardware}.rc
        ///import /vendor/etc/init/hw/init.${ro.hardware}.rc
        ///import /init.usb.configfs.rc
        ///import /init.${ro.zygote}.rc
        ///
        ///on early-init
        ///    # Set init and its forked children&apos;s oom_adj.
        ///    write /proc/1/oom_score_adj -1000
        ///
        ///    # Disable sysrq from keyboard        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string init_lineage16 {
            get {
                return ResourceManager.GetString("init_lineage16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Copyright (C) 2012 The Android Open Source Project
        ///#
        ///# IMPORTANT: Do not create world writable files or directories.
        ///# This is a common source of Android security bugs.
        ///#
        ///
        ///import /init.environ.rc
        ///import /system/etc/init/hw/init.usb.rc
        ///import /init.${ro.hardware}.rc
        ///import /vendor/etc/init/hw/init.${ro.hardware}.rc
        ///import /system/etc/init/hw/init.usb.configfs.rc
        ///import /system/etc/init/hw/init.${ro.zygote}.rc
        ///
        ///# Cgroups are mounted right before early-init using list from /etc/cgroups.json
        ///on  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string init_lineage18 {
            get {
                return ResourceManager.GetString("init_lineage18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Copyright (C) 2012 The Android Open Source Project
        ///#
        ///# IMPORTANT: Do not create world writable files or directories.
        ///# This is a common source of Android security bugs.
        ///#
        ///
        ///import /init.environ.rc
        ///import /system/etc/init/hw/init.usb.rc
        ///import /init.${ro.hardware}.rc
        ///import /vendor/etc/init/hw/init.${ro.hardware}.rc
        ///import /system/etc/init/hw/init.usb.configfs.rc
        ///import /system/etc/init/hw/init.${ro.zygote}.rc
        ///
        ///# Cgroups are mounted right before early-init using list from /etc/cgroups.json
        ///on  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string init_lineage20 {
            get {
                return ResourceManager.GetString("init_lineage20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iptables {
            get {
                object obj = ResourceManager.GetObject("iptables", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Languages&gt;
        ///	&lt;Language code=&quot;en&quot;&gt;
        ///		&lt;Text key=&quot;device&quot;&gt;Devices&lt;/Text&gt;
        ///		&lt;Text key=&quot;auto&quot;&gt;Automation&lt;/Text&gt;
        ///		&lt;Text key=&quot;view&quot;&gt;View Screen&lt;/Text&gt;
        ///	&lt;/Language&gt;
        ///	&lt;Language code=&quot;vi&quot;&gt;
        ///		&lt;Text key=&quot;device&quot;&gt;Thiết bị&lt;/Text&gt;
        ///		&lt;Text key=&quot;auto&quot;&gt;Tự động hóa&lt;/Text&gt;
        ///		&lt;Text key=&quot;view&quot;&gt;Xem màn hình&lt;/Text&gt;
        ///	&lt;/Language&gt;
        ///&lt;/Languages&gt;.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] libusb_1_0 {
            get {
                object obj = ResourceManager.GetObject("libusb_1_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lichtrinh_0 {
            get {
                object obj = ResourceManager.GetObject("lichtrinh_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap light_mode {
            get {
                object obj = ResourceManager.GetObject("light_mode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap luotchay_0 {
            get {
                object obj = ResourceManager.GetObject("luotchay_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7C:03:AB
        ///9C:2E:A1
        ///9C:99:A0
        ///A0:86:C6
        ///A4:45:19
        ///A4:4B:D5
        ///A4:50:46
        ///A8:9C:ED
        ///AC:C1:EE
        ///AC:F7:F3
        ///9C:28:F7
        ///98:FA:E3
        ///98:F6:21
        ///7C:1D:D9
        ///7C:2A:DB
        ///7C:D6:61
        ///7C:FD:6B
        ///80:35:C1
        ///80:AD:16
        ///8C:BE:BE
        ///90:78:B2
        ///94:87:E0
        ///B0:E2:35
        ///B4:C4:FC
        ///BC:7F:A4
        ///E4:46:DA
        ///E8:5A:8B
        ///EC:D0:9F
        ///F0:B4:29
        ///F4:30:8B
        ///F4:60:E2
        ///F4:8B:32
        ///F4:F5:DB
        ///F8:A4:5F
        ///E0:DC:FF
        ///E0:CC:F8
        ///E0:62:67
        ///C4:0B:CB
        ///C4:6A:B7
        ///C8:3D:DC
        ///D0:9C:7A
        ///D4:97:0B
        ///D8:32:E3
        ///D8:63:75
        ///D8:CE:3A
        ///E0:1F:88
        ///FC:64:BA
        ///00:9E:C8
        ///18:59:36
        ///18:F0:E4
        ///1C:CC:D6
        ///20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mac {
            get {
                return ResourceManager.GetString("mac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robinson
        ///Simmons
        ///Potter
        ///Jimenez
        ///Molina
        ///Lynn
        ///Ryan
        ///Branch
        ///Hunter
        ///Booker
        ///Russo
        ///Dougherty
        ///Goodwin
        ///Sexton
        ///Lin
        ///Benjamin
        ///Huber
        ///Garcia
        ///Richardson
        ///Mckay
        ///Hines
        ///Rose
        ///Stark
        ///Wright
        ///Harper
        ///Keller
        ///Michael
        ///Campbell
        ///Li
        ///Hooper
        ///Spears
        ///Griffith
        ///Irwin
        ///Mendez
        ///Ayers
        ///Park
        ///Holder
        ///Knapp
        ///Wiggins
        ///Mcfarland
        ///Cross
        ///Mueller
        ///Merritt
        ///Cooley
        ///Wong
        ///Sherman
        ///Jacobs
        ///Weiss
        ///Barber
        ///Camacho
        ///Campos
        ///Fernandez
        ///Lara
        ///Morrow
        ///Weaver
        ///Baxter
        ///Welch
        ///Maddox
        ///Beasley
        ///Herman
        ///Duncan
        ///Wall
        ///Castaneda
        ///Henry        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string names {
            get {
                return ResourceManager.GetString("names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nhiemvu_0 {
            get {
                object obj = ResourceManager.GetObject("nhiemvu_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @cmd
        ///.
        /// </summary>
        internal static string open_a_terminal_here {
            get {
                return ResourceManager.GetString("open_a_terminal_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quanlynguoidung_0 {
            get {
                object obj = ResourceManager.GetObject("quanlynguoidung_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quanlyungdung_0 {
            get {
                object obj = ResourceManager.GetObject("quanlyungdung_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] redsocks {
            get {
                object obj = ResourceManager.GetObject("redsocks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] redsocks2 {
            get {
                object obj = ResourceManager.GetObject("redsocks2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reload {
            get {
                object obj = ResourceManager.GetObject("reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap resartPhone {
            get {
                object obj = ResourceManager.GetObject("resartPhone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap router_0 {
            get {
                object obj = ResourceManager.GetObject("router_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] scrcpy {
            get {
                object obj = ResourceManager.GetObject("scrcpy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///scrcpy.exe --pause-on-exit=if-error %*
        ///.
        /// </summary>
        internal static string scrcpy_console {
            get {
                return ResourceManager.GetString("scrcpy_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strCommand = &quot;cmd /c scrcpy.exe&quot;
        ///
        ///For Each Arg In WScript.Arguments
        ///    strCommand = strCommand &amp; &quot; &quot;&quot;&quot; &amp; replace(Arg, &quot;&quot;&quot;&quot;, &quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;) &amp; &quot;&quot;&quot;&quot;
        ///Next
        ///
        ///CreateObject(&quot;Wscript.Shell&quot;).Run strCommand, 0, false
        ///.
        /// </summary>
        internal static string scrcpy_noconsole {
            get {
                return ResourceManager.GetString("scrcpy_noconsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] scrcpy_server {
            get {
                object obj = ResourceManager.GetObject("scrcpy_server", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SDL2 {
            get {
                object obj = ResourceManager.GetObject("SDL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap setting_0 {
            get {
                object obj = ResourceManager.GetObject("setting_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] swresample_5 {
            get {
                object obj = ResourceManager.GetObject("swresample_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thanhtoan_0 {
            get {
                object obj = ResourceManager.GetObject("thanhtoan_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tun2socks {
            get {
                object obj = ResourceManager.GetObject("tun2socks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap updated {
            get {
                object obj = ResourceManager.GetObject("updated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 97.0.4692.98_469209803
        ///96.0.4664.104_466410403
        ///95.0.4638.50_463805003
        ///94.0.4606.71_460607103
        ///93.0.4577.82_457708203
        ///92.0.4515.159_451515903
        ///91.0.4472.164_447216403.
        /// </summary>
        internal static string webview {
            get {
                return ResourceManager.GetString("webview", resourceCulture);
            }
        }
    }
}
